services:
    _defaults:
        autowire: true
        autoconfigure: true

    Juga\Todo\Tests\Behat\:
        resource: '../tests/Behat/*'

    Juga\Todo\Tests\Services\:
        resource: '../tests/Services/*'
        public: true
